# Generated by Django 5.0.2 on 2024-02-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda')], max_length=50)),
                ('model', models.CharField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(help_text='Enter the description of the car')),
                ('serial_num', models.CharField(unique=True)),
                ('manu_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
