# Generated by Django 5.0.2 on 2024-02-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
